//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.OfficeModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pms.OfficeModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string CurrenciesItemName {
            get {
                return ResourceManager.GetString("CurrenciesItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your currencies.
        /// </summary>
        internal static string CurrenciesItemToolTip {
            get {
                return ResourceManager.GetString("CurrenciesItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string DiscountsItemName {
            get {
                return ResourceManager.GetString("DiscountsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your discounts.
        /// </summary>
        internal static string DiscountsItemToolTip {
            get {
                return ResourceManager.GetString("DiscountsItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payforms.
        /// </summary>
        internal static string PayformsItemName {
            get {
                return ResourceManager.GetString("PayformsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your payforms.
        /// </summary>
        internal static string PayformsItemToolTip {
            get {
                return ResourceManager.GetString("PayformsItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Management.
        /// </summary>
        internal static string PmsOfficeModule {
            get {
                return ResourceManager.GetString("PmsOfficeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the POSenvironment.
        /// </summary>
        internal static string PmsOfficeModuleToolTip {
            get {
                return ResourceManager.GetString("PmsOfficeModuleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales families.
        /// </summary>
        internal static string SalesFamiliesItemName {
            get {
                return ResourceManager.GetString("SalesFamiliesItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales families.
        /// </summary>
        internal static string SalesFamiliesItemToolTip {
            get {
                return ResourceManager.GetString("SalesFamiliesItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales items.
        /// </summary>
        internal static string SalesItemsItemName {
            get {
                return ResourceManager.GetString("SalesItemsItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales items.
        /// </summary>
        internal static string SalesItemsItemToolTip {
            get {
                return ResourceManager.GetString("SalesItemsItemToolTip", resourceCulture);
            }
        }
    }
}
