
// This file has been generated by the GUI designer. Do not modify.
namespace Devices.GtkUi
{
	public partial class BuzzerWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Devices.GtkUi.BuzzerWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Devices.GtkUi.BuzzerWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
