//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.BackOffice.Module.Pms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poseidon.BackOffice.Module.Pms.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string CurrencyModule {
            get {
                return ResourceManager.GetString("CurrencyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your currencies.
        /// </summary>
        internal static string CurrencyModuleTooltip {
            get {
                return ResourceManager.GetString("CurrencyModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts.
        /// </summary>
        internal static string DiscountModule {
            get {
                return ResourceManager.GetString("DiscountModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your discounts.
        /// </summary>
        internal static string DiscountModuleTooltip {
            get {
                return ResourceManager.GetString("DiscountModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payforms.
        /// </summary>
        internal static string PayformModule {
            get {
                return ResourceManager.GetString("PayformModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your payforms.
        /// </summary>
        internal static string PayformModuleTooltip {
            get {
                return ResourceManager.GetString("PayformModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS Management.
        /// </summary>
        internal static string PmsOfficeModule {
            get {
                return ResourceManager.GetString("PmsOfficeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your POS environment.
        /// </summary>
        internal static string PmsOfficeModuleTooltip {
            get {
                return ResourceManager.GetString("PmsOfficeModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales family groups.
        /// </summary>
        internal static string SalesFamilyGroupModule {
            get {
                return ResourceManager.GetString("SalesFamilyGroupModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales family groups.
        /// </summary>
        internal static string SalesFamilyGroupModuleTooltip {
            get {
                return ResourceManager.GetString("SalesFamilyGroupModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales families.
        /// </summary>
        internal static string SalesFamilyModule {
            get {
                return ResourceManager.GetString("SalesFamilyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales families.
        /// </summary>
        internal static string SalesFamilyModuleTooltip {
            get {
                return ResourceManager.GetString("SalesFamilyModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales items.
        /// </summary>
        internal static string SalesItemModule {
            get {
                return ResourceManager.GetString("SalesItemModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your sales items.
        /// </summary>
        internal static string SalesItemModuleTooltip {
            get {
                return ResourceManager.GetString("SalesItemModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiters.
        /// </summary>
        internal static string WaiterModule {
            get {
                return ResourceManager.GetString("WaiterModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your waiters.
        /// </summary>
        internal static string WaiterModuleTooltip {
            get {
                return ResourceManager.GetString("WaiterModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiter teams.
        /// </summary>
        internal static string WaiterTeamModule {
            get {
                return ResourceManager.GetString("WaiterTeamModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your waiter teams.
        /// </summary>
        internal static string WaiterTeamModuleTooltip {
            get {
                return ResourceManager.GetString("WaiterTeamModuleTooltip", resourceCulture);
            }
        }
    }
}
