//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.BackOffice.Module.Ics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poseidon.BackOffice.Module.Ics.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditUnitTypeView_Name {
            get {
                return ResourceManager.GetString("EditUnitTypeView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        public static string Heading_Contraction {
            get {
                return ResourceManager.GetString("Heading_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        public static string Heading_Factor {
            get {
                return ResourceManager.GetString("Heading_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main stock.
        /// </summary>
        public static string Heading_MainStock {
            get {
                return ResourceManager.GetString("Heading_MainStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Heading_Name {
            get {
                return ResourceManager.GetString("Heading_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Heading_Parent {
            get {
                return ResourceManager.GetString("Heading_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU.
        /// </summary>
        public static string Heading_Plu {
            get {
                return ResourceManager.GetString("Heading_Plu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Heading_Purchase {
            get {
                return ResourceManager.GetString("Heading_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe.
        /// </summary>
        public static string Heading_Recipe {
            get {
                return ResourceManager.GetString("Heading_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Control.
        /// </summary>
        public static string IcsOfficeModule {
            get {
                return ResourceManager.GetString("IcsOfficeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your inventory at one glance.
        /// </summary>
        public static string IcsOfficeModuleTooltip {
            get {
                return ResourceManager.GetString("IcsOfficeModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production items.
        /// </summary>
        public static string ProductionItemModule {
            get {
                return ResourceManager.GetString("ProductionItemModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your production items.
        /// </summary>
        public static string ProductionItemModuleTooltip {
            get {
                return ResourceManager.GetString("ProductionItemModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production items.
        /// </summary>
        public static string ProductionItemsView_Title {
            get {
                return ResourceManager.GetString("ProductionItemsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase families.
        /// </summary>
        public static string PurchaseFamiliesView_Title {
            get {
                return ResourceManager.GetString("PurchaseFamiliesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase families.
        /// </summary>
        public static string PurchaseFamilyModule {
            get {
                return ResourceManager.GetString("PurchaseFamilyModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your purchase families.
        /// </summary>
        public static string PurchaseFamilyModuleTooltip {
            get {
                return ResourceManager.GetString("PurchaseFamilyModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase items.
        /// </summary>
        public static string PurchaseItemModule {
            get {
                return ResourceManager.GetString("PurchaseItemModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your purchase items.
        /// </summary>
        public static string PurchaseItemModuleTooltip {
            get {
                return ResourceManager.GetString("PurchaseItemModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase items.
        /// </summary>
        public static string PurchaseItemsView_Title {
            get {
                return ResourceManager.GetString("PurchaseItemsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipeModule {
            get {
                return ResourceManager.GetString("RecipeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your recipes.
        /// </summary>
        public static string RecipeModuleTooltip {
            get {
                return ResourceManager.GetString("RecipeModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipes.
        /// </summary>
        public static string RecipesView_Title {
            get {
                return ResourceManager.GetString("RecipesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string StockModule {
            get {
                return ResourceManager.GetString("StockModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your stocks.
        /// </summary>
        public static string StockModuleTooltip {
            get {
                return ResourceManager.GetString("StockModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stocks.
        /// </summary>
        public static string StocksView_Title {
            get {
                return ResourceManager.GetString("StocksView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitModule {
            get {
                return ResourceManager.GetString("UnitModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your units.
        /// </summary>
        public static string UnitModuleTooltip {
            get {
                return ResourceManager.GetString("UnitModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string UnitsView_Title {
            get {
                return ResourceManager.GetString("UnitsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit types.
        /// </summary>
        public static string UnitTypeModule {
            get {
                return ResourceManager.GetString("UnitTypeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your unit types.
        /// </summary>
        public static string UnitTypeModuleTooltip {
            get {
                return ResourceManager.GetString("UnitTypeModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit types.
        /// </summary>
        public static string UnitTypesView_Title {
            get {
                return ResourceManager.GetString("UnitTypesView_Title", resourceCulture);
            }
        }
    }
}
