//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ums.OfficeModule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ums.OfficeModule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user role....
        /// </summary>
        public static string EditUserRole_AddNewUserRole {
            get {
                return ResourceManager.GetString("EditUserRole_AddNewUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user role.
        /// </summary>
        public static string EditUserRole_EditUserRole {
            get {
                return ResourceManager.GetString("EditUserRole_EditUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Name:.
        /// </summary>
        public static string EditUserView_Name {
            get {
                return ResourceManager.GetString("EditUserView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _User role:.
        /// </summary>
        public static string EditUserView_UserRole {
            get {
                return ResourceManager.GetString("EditUserView_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string KeyRole {
            get {
                return ResourceManager.GetString("KeyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string KeyRoles {
            get {
                return ResourceManager.GetString("KeyRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string KeyUser {
            get {
                return ResourceManager.GetString("KeyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string KeyUsers {
            get {
                return ResourceManager.GetString("KeyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ListUserRoles_Header_Name {
            get {
                return ResourceManager.GetString("ListUserRoles_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string ListUserRolesTitle {
            get {
                return ResourceManager.GetString("ListUserRolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user....
        /// </summary>
        public static string ListUsers_Add_ToolTip {
            get {
                return ResourceManager.GetString("ListUsers_Add_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string ListUsers_Edit_ToolTip {
            get {
                return ResourceManager.GetString("ListUsers_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ListUsers_Header_Name {
            get {
                return ResourceManager.GetString("ListUsers_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role.
        /// </summary>
        public static string ListUsers_Header_UserRole {
            get {
                return ResourceManager.GetString("ListUsers_Header_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string ListUsers_Remove_ToolTip {
            get {
                return ResourceManager.GetString("ListUsers_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ListUsersTitle {
            get {
                return ResourceManager.GetString("ListUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UmsOfficeModule {
            get {
                return ResourceManager.GetString("UmsOfficeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users of the system, edit their profiles and their rights.
        /// </summary>
        public static string UmsOfficeModuleToolTip {
            get {
                return ResourceManager.GetString("UmsOfficeModuleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string UserModel_Name_missing {
            get {
                return ResourceManager.GetString("UserModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role is missing.
        /// </summary>
        public static string UserModel_UserRole_missing {
            get {
                return ResourceManager.GetString("UserModel_UserRole_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is missing.
        /// </summary>
        public static string UserRoleModel_Name_missing {
            get {
                return ResourceManager.GetString("UserRoleModel_Name_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string UserRolesItemName {
            get {
                return ResourceManager.GetString("UserRolesItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user roles.
        /// </summary>
        public static string UserRolesItemToolTip {
            get {
                return ResourceManager.GetString("UserRolesItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersItemName {
            get {
                return ResourceManager.GetString("UsersItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit users.
        /// </summary>
        public static string UsersItemToolTip {
            get {
                return ResourceManager.GetString("UsersItemToolTip", resourceCulture);
            }
        }
    }
}
