//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseidon.BackOffice.Module.Ums.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Poseidon.BackOffice.Module.Ums.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Heading_Name {
            get {
                return ResourceManager.GetString("Heading_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Heading_UserRole {
            get {
                return ResourceManager.GetString("Heading_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UmsOfficeModule {
            get {
                return ResourceManager.GetString("UmsOfficeModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users of the system, edit their profiles and their rights.
        /// </summary>
        public static string UmsOfficeModuleTooltip {
            get {
                return ResourceManager.GetString("UmsOfficeModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserModule {
            get {
                return ResourceManager.GetString("UserModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your users.
        /// </summary>
        public static string UserModuleTooltip {
            get {
                return ResourceManager.GetString("UserModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string UserRoleModule {
            get {
                return ResourceManager.GetString("UserRoleModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your user roles.
        /// </summary>
        public static string UserRoleModuleTooltip {
            get {
                return ResourceManager.GetString("UserRoleModuleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User roles.
        /// </summary>
        public static string UserRolesView_Title {
            get {
                return ResourceManager.GetString("UserRolesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersView_Title {
            get {
                return ResourceManager.GetString("UsersView_Title", resourceCulture);
            }
        }
    }
}
